### ISSUE TITLE
Add credit to the origin of the music.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [Co-Science/CountMeDown#4]
http://github.com/Co-Science/CountMeDown/blob/main/resources/audio/microsoftTime.mp3

**Comment by Joel-Nickson** [comment]
Could you add that...
It was from twitter account the ms announced the windows 11 release

**Comment by Joel-Nickson** [comment]
Open to anyone who wants to contribute [hacktoberfest]:

- [ ] Add the twitter page of windows to the html file

**Comment by ajit-kumar014** [comment]
I searched for the source of the audio file it was from the song " So Bright -by pretty lights " . I couldn't find the audio on the twitter page of windows.

**Comment by Joel-Nickson** [comment]
It was one of the video file (not an audio file) from the twitter page. I just extracted the audio from that file for the windows release event countdown.

**Comment by ajit-kumar014** [comment]
I want to work on this assign this to me.

**Comment by Joel-Nickson** [comment]
#6  merged
